# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  CI:
    sh: "[[ -n $CI ]] && echo true || echo false"

tasks:

  hooks:
    if: '{{ eq .CI "false" }}'
    sources:
      - lefthook.yml
    generates:
      - .git/hooks/pre-commit
      - .git/hooks/pre-push
    cmd: lefthook install

  install:
    desc: Install LazyVim plugins
    sources:
      - lazy-lock.json
    cmds:
      - task: hooks
      - nvim --headless "+Lazy! install" +qa

  update:
    desc: Update LazyVim plugins
    generates:
      - lazy-lock.json
    cmd: nvim --headless "+Lazy! update" +qa

  lint:
    desc: Lint codebase
    deps:
      - task: lint:lua
      - task: lint:md
      - task: lint:shell
      - task: lint:ci

  format:
    desc: Format codebase
    deps:
      - task: format:lua
      - task: format:md

  test:
    desc: Run full test pipeline
    cmds:
      - task: test:unit
      - task: test:integration

  lint:lua:
    desc: Lint Lua sources and tests
    if: command -v stylua && command -v selene
    sources:
      - ./**/*.lua
    cmds:
      - stylua --check {{ .CLI_ARGS | default "." }}
      - selene {{ .CLI_ARGS | default "." }}

  lint:md:
    desc: Lint Markdown files
    if: command -v markdownlint-cli2
    sources:
      - ./**/*.md
    cmd: markdownlint-cli2 {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}"**/*.md"{{end}}

  lint:shell:
    desc: Lint Shell scripts
    if: command -v shellcheck
    sources:
      - ./**/*.sh
    cmd: '{{if .CLI_ARGS}}shellcheck {{ .CLI_ARGS }}{{else}}find . -type f -name "*.sh" -exec shellcheck {} \;{{end}}'

  lint:ci:
    desc: Lint GitHub Actions workflows
    sources:
      - .github/workflows/*.yml
    cmds:
      - task: actionlint
      - task: zizmor

  actionlint:
    desc: Run actionlint
    if: command -v actionlint
    cmd: actionlint

  zizmor:
    desc: Run zizmor
    if: command -v zizmor
    cmd: zizmor --persona auditor .github/workflows
    env:
      GITHUB_TOKEN:
        sh: gh auth token

  format:lua:
    desc: Format Lua sources and tests
    if: command -v stylua
    sources:
      - ./**/*.lua
    cmd: stylua {{ .CLI_ARGS | default "." }}

  format:md:
    desc: Fix auto-fixable Markdown lint issues
    if: command -v markdownlint-cli2
    sources:
      - ./**/*.md
    cmd: markdownlint-cli2 --fix {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}"**/*.md"{{end}}

  test:unit:
    desc: Run unit tests
    if: command -v busted
    cmd: busted --run=unit {{ .CLI_ARGS | default "" }}

  test:integration:
    desc: Run integration tests
    if: command -v busted
    cmd: busted --run=integration {{ .CLI_ARGS | default "" }}
