# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'


tasks:

  hooks:
    internal: true
    sources:
      - lefthook.yml
    generates:
      - .git/hooks/pre-commit
      - .git/hooks/pre-push
    cmd: lefthook install

  install:
    desc: Install LazyVim plugins
    sources:
      - lazy-lock.json
    cmds:
      - task: hooks
      - nvim --headless "+Lazy! install" +qa

  update:
    desc: Update LazyVim plugins
    generates:
      - lazy-lock.json
    cmd: nvim --headless "+Lazy! update" +qa

  lint:
    desc: Lint codebase
    cmds:
      - task: lint:lua
      - task: lint:format
      - task: lint:md
      - task: lint:shell

  format:
    desc: Format codebase
    cmds:
      - task: format:lua
      - task: format:md

  test:
    desc: Run full test pipeline
    cmds:
      - task: test:unit
      - task: test:integration

  lint:lua:
    desc: Lint Lua sources and tests
    sources:
      - ./**/*.lua
    cmd: selene {{ .CLI_ARGS | default "." }}

  lint:format:
    desc: Check Lua formatting
    sources:
      - ./**/*.lua
    cmd: stylua --check {{ .CLI_ARGS | default "." }}

  lint:md:
    desc: Lint Markdown files
    sources:
      - ./**/*.md
    cmd: markdownlint-cli2 {{ .CLI_ARGS | default "./**/*.md" }}

  lint:shell:
    desc: Lint Shell scripts
    sources:
      - ./**/*.sh
    cmd: '{{if .CLI_ARGS}}shellcheck {{ .CLI_ARGS }}{{else}}find . -type f -name "*.sh" -exec shellcheck {} \;{{end}}'

  format:lua:
    desc: Format Lua sources and tests
    sources:
      - ./**/*.lua
    cmd: stylua {{ .CLI_ARGS | default "." }}

  format:md:
    desc: Fix auto-fixable Markdown lint issues
    sources:
      - ./**/*.md
    cmd: markdownlint-cli2 --fix {{ .CLI_ARGS | default "./**/*.md" }}

  test:unit:
    desc: Run unit tests
    sources:
      - ./
    cmd: busted --run=unit {{ .CLI_ARGS | default "" }}

  test:integration:
    desc: Run integration tests
    cmd: busted --run=integration {{ .CLI_ARGS | default "" }}
